version: "3.4"
services:

    db:
      image: mariadb:10.3
      container_name: dmh-db
      volumes:
        - ./dbdata/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=default
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
      ports:
        - "3306:3306"

    phpmyadmin:
      container_name: phpMyAdmin
      image: phpmyadmin
      ports:
        - "8181:80"
      environment:
        - SESSION_TIMEOUT=604800 # 7 days session timeout
        - UPLOAD_LIMIT=300M
#       - PMA_ARBITRARY=1 # Uncomment this if you want to be able to choose the db container e.g. "db"

      depends_on:
        - db

    nginx:
      container_name: dmh-nginx
      build:
        context: ./nginx

      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
        - php

    php:
#      build: ../../php-fpm
      build: ./php-fpm
      container_name: dmh-php
      working_dir: /var/www
      volumes:
        - ..:/var/www
        - ./php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini


